function welfare = computeWelfare(vf_start, m0)
% COMPUTEWELFARE Computes average welfare given value functions and initial distribution.
%
%   welfare = computeWelfare(vf_start, m0)
%
%   INPUTS:
%       vf_start - Struct with fields .V and .Vn at time 0
%       m0       - [Nagents x 1] struct array with initial agent states
%
%   OUTPUT:
%       welfare  - Scalar average of value function across agents
%
%   AUTHOR: Auto-generated by ChatGPT
%   -------------------------------------------------------------------------
    numAgents = numel(m0);
    vals = zeros(numAgents,1);
    for i = 1:numAgents
        s   = m0(i).state;
        w   = m0(i).wealth;
        loc = m0(i).location;
        if m0(i).network == 1
            vals(i) = vf_start.Vn(s, w, loc);
        else
            vals(i) = vf_start.V(s, w, loc);
        end
    end
    welfare = mean(vals);
end
